# Generated by Django 6.0.2 on 2026-02-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creaed_at',
            new_name='created_at',
        ),
    ]
